---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls
  - pushd MCAnimationViewExample
  - pod install
  - popd

script:
#  - xctool workspace MCAnimationViewExample/MCAnimationViewExample.xcworkspace -scheme MCAnimationViewExample build test -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
  - xctool workspace MCAnimationViewExample/MCAnimationViewExample.xcworkspace -scheme MCAnimationViewExample build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO

after_success:
#  - ./coveralls.rb --extension m --exclude-folder MCAnimationViewExample/MCAnimationViewExample
